#配置数据源
spring:
  redis:
    #数据库索引
    database: 1
    host: 192.168.0.2
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000
#  redis:
#    #数据库索引
#    database: 0
#    host: 47.88.87.204
#    port: 30000
#    password: OPandaDev123
#    #连接超时时间
#    timeout: 5000
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.0.2:3306/dev?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: dev
      password: 123456
#      url: jdbc:log4jdbc:mysql://47.88.87.204:30001/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
#      username: dev
#      password: OPandaDev123

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://root:123456@192.168.0.2
      database: dev

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 7200000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true